name: ualabis_dart
description: A basic Uala SDK Dart Implementation
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
